name = "GraceFt"
version = "3.0.1"

[build]
stdcxx = 20
target = "static"
define = ["M_PI=3.1415926535", "UNICODE", "_UNICODE"]
generator = "MinGW Makefiles"
jobs = 0

[dependencies]
EGE = { git = "@Anglebase/EGE", version = "0.1.0" }

[link]
libs = ["ws2_32"]